import 'package:flutter/painting.dart';

const javaTheme = {
  'name': TextStyle(color: Color(0xFFFF7F11), fontWeight: FontWeight.bold),
  'tag': TextStyle(color: Color(0xFF778899)),
  'meta': TextStyle(color: Color(0xFF778899)),
  'root': TextStyle(color: Color(0xFFFFFFFF)),
  'subst': TextStyle(color: Color(0xFF000000)),
  'comment': TextStyle(color: Color(0xFF888888)),
  'keyword': TextStyle(fontWeight: FontWeight.bold),
  'attribute': TextStyle(fontWeight: FontWeight.bold),
  'selector-tag': TextStyle(fontWeight: FontWeight.bold),
  'meta-keyword': TextStyle(fontWeight: FontWeight.bold),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'type': TextStyle(color: Color(0xFF4286f4)),
  'string': TextStyle(color: Color(0xFF62bcbc)),
  'number': TextStyle(color: Color(0xFFBC6060)),
  'selector-id': TextStyle(color: Color(0xFF4286f4)),
  'selector-class': TextStyle(color: Color(0xFF4286f4)),
  'quote': TextStyle(color: Color(0xFF4286f4)),
  'template-tag': TextStyle(color: Color(0xFF4286f4)),
  'deletion': TextStyle(color: Color(0xFF4286f4)),
  'title': TextStyle(color: Color(0xFF4286f4), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xFF4286f4), fontWeight: FontWeight.bold),
  'regexp': TextStyle(color: Color(0xFFBC6060)),
  'symbol': TextStyle(color: Color(0xFFBC6060)),
  'variable': TextStyle(color: Color(0xFFBC6060)),
  'template-variable': TextStyle(color: Color(0xFFBC6060)),
  'link': TextStyle(color: Color(0xFFBC6060)),
  'selector-attr': TextStyle(color: Color(0xFFBC6060)),
  'selector-pseudo': TextStyle(color: Color(0xFFBC6060)),
  'literal': TextStyle(color: Color(0xFF62bcbc)),
  'built_in': TextStyle(color: Color(0xFF25c6c6)),
  'bullet': TextStyle(color: Color(0xFF25c6c6)),
  'code': TextStyle(color: Color(0xFF25c6c6)),
  'addition': TextStyle(color: Color(0xFF25c6c6)),
  'meta-string': TextStyle(color: Color(0xFF4d99bf)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
