import 'package:flutter/painting.dart';

const tigerTheme = {
  'name': TextStyle(color: Color(0xFFFFA500), fontWeight: FontWeight.bold),
  'tag': TextStyle(color: Color(0xFF808080)),
  'meta': TextStyle(color: Color(0xFF808080)),
  'root': TextStyle(color: Color(0xFFFFFFFF)),
  'subst': TextStyle(color: Color(0xFF000000)),
  'comment': TextStyle(color: Color(0xFF888888)),
  'keyword': TextStyle(fontWeight: FontWeight.bold),
  'attribute': TextStyle(fontWeight: FontWeight.bold),
  'selector-tag': TextStyle(fontWeight: FontWeight.bold),
  'meta-keyword': TextStyle(fontWeight: FontWeight.bold),
  'doctag': TextStyle(fontWeight: FontWeight.bold),
  'type': TextStyle(color: Color(0xFFFFA500)),
  'string': TextStyle(color: Color(0xFFFFA500)),
  'number': TextStyle(color: Color(0xFFFFA500)),
  'selector-id': TextStyle(color: Color(0xFFFFA500)),
  'selector-class': TextStyle(color: Color(0xFFFFA500)),
  'quote': TextStyle(color: Color(0xFFFFA500)),
  'template-tag': TextStyle(color: Color(0xFFFFA500)),
  'deletion': TextStyle(color: Color(0xFFFFA500)),
  'title': TextStyle(color: Color(0xFFFFA500), fontWeight: FontWeight.bold),
  'section': TextStyle(color: Color(0xFFFFA500), fontWeight: FontWeight.bold),
  'regexp': TextStyle(color: Color(0xFFBC6060)),
  'symbol': TextStyle(color: Color(0xFFBC6060)),
  'variable': TextStyle(color: Color(0xFFBC6060)),
  'template-variable': TextStyle(color: Color(0xFFBC6060)),
  'link': TextStyle(color: Color(0xFFBC6060)),
  'selector-attr': TextStyle(color: Color(0xFFBC6060)),
  'selector-pseudo': TextStyle(color: Color(0xFFBC6060)),
  'literal': TextStyle(color: Color(0xFF000000)),
  'built_in': TextStyle(color: Color(0xFFFFA500)),
  'bullet': TextStyle(color: Color(0xFFFFA500)),
  'code': TextStyle(color: Color(0xFFFFA500)),
  'addition': TextStyle(color: Color(0xFFFFA500)),
  'meta-string': TextStyle(color: Color(0xFF4D99BF)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
};
