name: Flutter CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      - name: Update Flutter and Dart
        run: |
          flutter upgrade
          flutter pub global activate dart_style
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}